version: '3.8'

services:
  user-service:
    build:
      context: ./user-service  
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo
    volumes:
      - ./user-service:/app
      - /app/node_modules
    networks:
      - node-network

  room-service:
    build:
      context: ./room-service  
      dockerfile: Dockerfile
    ports:
      - '3002:3000'  
    depends_on:
      - mongo
    volumes:
      - ./room-service:/app
      - /app/node_modules
    networks:
      - node-network

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - node-network

  angular-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      - node-network

volumes:
  mongodb:

networks:
  node-network:
    driver: bridge
