version: '3.8'

services:
  product-service:
    build:
      context: ./user-service  
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo

  order-service:
    build:
      context: ./room-service  
      dockerfile: Dockerfile
    ports:
      - '3002:3000'  
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  angular-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
